services:
  - type: static
    name: fresh-kart-admin
    rootDir: admin_panel
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false          # Set this manually in the Render dashboard
      - key: VITE_SUPABASE_ANON_KEY
        sync: false          # Set this manually in the Render dashboard
      - key: VITE_FIREBASE_VAPID_KEY
        value: BMfwxEJZsQyQ3tAYene3NboufNpOISbrcejF1LeE_bjgPlGmd0pdopb2zRSAC9zG7Y1-A8avcZXbemmtwnC_w6U
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
